# Generated by Django 4.2 on 2023-04-11 01:43

import contatos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=60, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=80, verbose_name='E-mail')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('descricao', models.TextField(blank=True, max_length=200, verbose_name='Descrição')),
                ('mostrar', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to=contatos.models.renomeia_foto)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contatos.categoria')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
